### ISSUE TITLE
somehow target/instance is mixed up?

### ISSUE THREAD

**Issue by DanielWeeber** [lwlcom/cisco_exporter#16]
I have three switches setup.
Somehow target/instance is mixed up/doubled between them?

```
cisco_up{hostname="<name1>", instance="<ip of name1>", job="cisco", target="<ip of name3>"}
cisco_up{hostname="<name1>", instance="<ip of name1>", job="cisco", target="<ip of name1>"} 
cisco_up{hostname="<name1>", instance="<ip of name1>", job="cisco", target="<ip of name2>"}
cisco_up{hostname="<name2>", instance="<ip of name2>", job="cisco", target="<ip of name3>"} 
cisco_up{hostname="<name2>", instance="<ip of name2>", job="cisco", target="<ip of name1>"}
cisco_up{hostname="<name2>", instance="<ip of name2>", job="cisco", target="<ip of name2>"}
cisco_up{hostname="<name3>", instance="<ip of name3>", job="cisco", target="<ip of name3>"} 
cisco_up{hostname="<name3>", instance="<ip of name3>", job="cisco", target="<ip of name1>"}
cisco_up{hostname="<name3>", instance="<ip of name3>", job="cisco", target="<ip of name2>"}
```

Prometheus config

```
- file_sd_configs:
  - files:
    - targets/cisco.json
  job_name: cisco
  metrics_path: /metrics
  params:
    module:
    - cisco
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - replacement: 127.0.0.1:9362
    target_label: __address__
```

targets/cisco.json:

```
[
    {
      "targets": [ "<ip of name3>" ],
      "labels": {
        "hostname": "<name3>"
      }
    },
    {
      "targets": [ "<ip of name2>" ],
      "labels": {
        "hostname": "<name2>"
      }
    },
    {
      "targets": [ "<ip of name1>" ],
      "labels": {
        "hostname": "<name1>"
      }
    }
  ]
```
